---
- name: include OS-specific variables
  include_vars: "RedHat.yml"

- name: download
  get_url:
    url: "http://xdebug.org/files/xdebug-{{ php_xdebug_version }}.tgz"
    dest: "{{ workspace }}/xdebug-{{ php_xdebug_version }}.tgz"

- name: untar
  unarchive:
    src: "{{ workspace }}/xdebug-{{ php_xdebug_version }}.tgz"
    dest: "{{ workspace }}"
    copy: no

- name: build
  shell: >
    {{ item }}
    chdir={{ workspace }}/xdebug-{{ php_xdebug_version | upper }}
    creates={{ workspace }}/xdebug-{{ php_xdebug_version | upper }}/modules/xdebug.so
  with_items:
    - phpize
    - ./configure
    - make

- name: ensure module exists
  file:
    path: "{{ php_xdebug_module_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: yes

- name: move module into place
  shell: >
    cp {{ workspace }}/xdebug-{{ php_xdebug_version | upper }}/modules/xdebug.so {{ php_xdebug_module_path }}/xdebug.so
    creates={{ php_xdebug_module_path }}/xdebug.so
  become: yes

- name: configure
  template:
    src: xdebug.ini.j2
    dest: "{{ php_ini_path }}/xdebug.ini"
    owner: root
    group: root
    mode: 0644
  become: yes
