---
workspace: /home/vagrant

php_xdebug_version: 2.4.0rc4

php_ini_path: /etc/php.d

php_xdebug_coverage_enable: 1
php_xdebug_default_enable: 1

php_xdebug_remote_enable: "false"
php_xdebug_remote_connect_back: "false"
php_xdebug_remote_host: localhost
php_xdebug_remote_port: "9000"
php_xdebug_remote_log: /tmp/xdebug.log
php_xdebug_remote_autostart: "false"
php_xdebug_idekey: ~
php_xdebug_max_nesting_level: 256
