---
- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
  tags:
    - nginx:restart

- name: validate nginx configuration
  become: yes
  command: nginx -t
  changed_when: false
  tags:
    - nginx:test

- name: reload nginx
  become: yes
  service:
    name: nginx
    state: reloaded
  tags:
    - nginx:reload

- name: start nginx
  become: yes
  service:
    name: nginx
    state: started
  tags:
    - nginx:start
