---
- name: install
  become: yes
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: php.packages
  when: php.packages is defined

- name: configure
  become: yes
  template:
    src: php.ini.j2
    dest: /etc/php.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - restart php-fpm

- name: configures runlevel
  become: yes
  service:
    name: php-fpm
    enabled: yes

- include: install-composer.yml
  when: php.install_composer
